-- Tabla de configuración general para la tienda
CREATE TABLE IF NOT EXISTS configuracion_general (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(64) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Ejemplo de inserción de variables iniciales
INSERT INTO configuracion_general (clave, valor, descripcion) VALUES
('correo_corporativo', '', 'Correo usado para notificaciones'),
('smtp_host', '', 'Host SMTP para envío de correos'),
('smtp_user', '', 'Usuario SMTP'),
('smtp_pass', '', 'Contraseña SMTP'),
('smtp_port', '587', 'Puerto SMTP'),
('smtp_secure', 'tls', 'Tipo de seguridad SMTP'),
('nombre_prefijo', 'TIENDA', 'Texto superior del encabezado de la tienda'),
('nombre_tienda', 'TVirtualGaming', 'Nombre principal visible de la tienda'),
('nombre_tienda_subtitulo', 'Tienda de monedas digitales', 'Texto complementario usado en el título del inicio y en la instalación de la app'),
('logo_tienda', '', 'Ruta del logo visible en el encabezado'),
('facebook', '', 'URL de Facebook de la tienda'),
('instagram', '', 'URL de Instagram de la tienda'),
('whatsapp', '', 'Número o enlace de WhatsApp de la tienda'),
('mensaje_whatsapp', '', 'Mensaje predefinido para el botón flotante de WhatsApp'),
('whatsapp_channel', '', 'URL del canal de WhatsApp de la tienda'),
('google_client_id', '', 'Client ID de Google para login y registro social'),
('google_client_secret', '', 'Client Secret de Google para login y registro social'),
('inicio_popup_tab_habilitado', '1', 'Activa o desactiva globalmente el tab y la función de la ventana inicial'),
('inicio_popup_activo', '1', 'Activa o desactiva la aparición de la ventana inicial en el index'),
('inicio_popup_video_activo', '0', 'Activa o desactiva la aparición de la ventana inicial con video en el index'),
('inicio_popup_frecuencia', 'per_session', 'Frecuencia con la que debe aparecer la ventana inicial en el index'),
('inicio_popup_nombre_canal', 'DanisA Gamer Store', 'Nombre visible del canal en la ventana inicial'),
('inicio_popup_video_url', '', 'Enlace de YouTube usado en la ventana inicial con video'),
('ff_bank_api_base_url', 'https://pagonorte.net', 'Enlace base de la API del banco para consultar movimientos'),
('ff_bank_posicion', '0', 'Posicion para la conexion al banco de Free Fire'),
('ff_bank_token', '', 'Token para la conexion al banco de Free Fire'),
('ff_bank_clave', '', 'Clave para la conexion al banco de Free Fire'),
('ff_api_usuario', '', 'Usuario para la API de Free Fire'),
('ff_api_clave', '', 'Clave para la API de Free Fire'),
('ff_api_tipo', 'recargaFreefire', 'Tipo para la API de Free Fire'),
('theme_bg_main', '#0A0F14', 'Color base del fondo general de la tienda'),
('theme_bg_alt', '#0E1722', 'Color usado en degradados y secciones secundarias'),
('theme_surface', '#111827', 'Color de tarjetas, paneles y modales'),
('theme_surface_alt', '#181F2A', 'Color alterno para cabecera, dropdowns y paneles internos'),
('theme_primary', '#22D3EE', 'Color principal del brillo, bordes y textos destacados'),
('theme_highlight', '#00FFF7', 'Color de realce para brillos y botones destacados'),
('theme_secondary', '#2DD4BF', 'Color secundario para degradados, hover y efectos'),
('theme_success', '#34D399', 'Color para acciones positivas y estados correctos'),
('theme_warning', '#F59E0B', 'Color para alertas y estados de revisión'),
('theme_danger', '#F87171', 'Color para cancelaciones, errores y alertas críticas'),
('theme_text', '#F8FAFC', 'Color principal del texto en la tienda'),
('theme_text_muted', '#CBD5E1', 'Color de textos secundarios, ayudas y descripciones'),
('theme_price_text', '#22D3EE', 'Color del monto principal en precios de juegos y paquetes'),
('theme_price_muted', '#94A3B8', 'Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_border', '#164E63', 'Color base de bordes, separadores y contenedores'),
('theme_button_primary', '#22D3EE', 'Color principal para botones, acciones y llamadas principales'),
('theme_button_secondary', '#2DD4BF', 'Color secundario para degradados y hover de botones'),
('theme_button_surface', '#0E1722', 'Color base para botones oscuros, menú y tarjetas seleccionables'),
('theme_float_whatsapp_bg', '#22C55E', 'Color principal del botón flotante de WhatsApp'),
('theme_float_whatsapp_text', '#F8FAFC', 'Color del texto e icono del botón flotante de WhatsApp'),
('theme_float_channel_bg', '#1F2937', 'Color principal del botón flotante del canal de difusión'),
('theme_float_channel_text', '#F8FAFC', 'Color del texto e icono del botón flotante del canal de difusión'),
('theme_custom_bg_main', '#0A0F14', 'Copia editable: Color base del fondo general de la tienda'),
('theme_custom_bg_alt', '#0E1722', 'Copia editable: Color usado en degradados y secciones secundarias'),
('theme_custom_surface', '#111827', 'Copia editable: Color de tarjetas, paneles y modales'),
('theme_custom_surface_alt', '#181F2A', 'Copia editable: Color alterno para cabecera, dropdowns y paneles internos'),
('theme_custom_primary', '#22D3EE', 'Copia editable: Color principal del brillo, bordes y textos destacados'),
('theme_custom_highlight', '#00FFF7', 'Copia editable: Color de realce para brillos y botones destacados'),
('theme_custom_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados, hover y efectos'),
('theme_custom_success', '#34D399', 'Copia editable: Color para acciones positivas y estados correctos'),
('theme_custom_warning', '#F59E0B', 'Copia editable: Color para alertas y estados de revisión'),
('theme_custom_danger', '#F87171', 'Copia editable: Color para cancelaciones, errores y alertas críticas'),
('theme_custom_text', '#F8FAFC', 'Copia editable: Color principal del texto en la tienda'),
('theme_custom_text_muted', '#CBD5E1', 'Copia editable: Color de textos secundarios, ayudas y descripciones'),
('theme_custom_price_text', '#22D3EE', 'Copia editable: Color del monto principal en precios de juegos y paquetes'),
('theme_custom_price_muted', '#94A3B8', 'Copia editable: Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_custom_border', '#164E63', 'Copia editable: Color base de bordes, separadores y contenedores'),
('theme_custom_button_primary', '#22D3EE', 'Copia editable: Color principal para botones, acciones y llamadas principales'),
('theme_custom_button_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados y hover de botones'),
('theme_custom_button_surface', '#0E1722', 'Copia editable: Color base para botones oscuros, menú y tarjetas seleccionables'),
('theme_custom_float_whatsapp_bg', '#22C55E', 'Copia editable: Color principal del botón flotante de WhatsApp'),
('theme_custom_float_whatsapp_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón flotante de WhatsApp'),
('theme_custom_float_channel_bg', '#1F2937', 'Copia editable: Color principal del botón flotante del canal de difusión'),
('theme_custom_float_channel_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón flotante del canal de difusión'),
('theme_startup_popup_surface', '#140D0E', 'Color base del panel principal de la ventana inicial'),
('theme_startup_popup_border', '#3D1C1A', 'Color del borde y contornos de la ventana inicial'),
('theme_startup_popup_accent', '#25D366', 'Color del icono principal, resaltes y brillo de la ventana inicial'),
('theme_startup_popup_chip', '#0E2B1B', 'Color de fondo para la insignia superior de la ventana inicial'),
('theme_startup_popup_button_text', '#F8FAFC', 'Color del texto e icono del botón principal de la ventana inicial'),
('theme_startup_video_popup_surface', '#1A2233', 'Color base del panel principal de la ventana inicial con video'),
('theme_startup_video_popup_border', '#314462', 'Color del borde y contornos de la ventana inicial con video'),
('theme_startup_video_popup_accent', '#F87171', 'Color de detalles destacados y botón de cierre de la ventana inicial con video'),
('theme_startup_video_popup_button_bg', '#25D366', 'Color principal del botón del canal en la ventana inicial con video'),
('theme_startup_video_popup_button_text', '#F8FAFC', 'Color del texto e icono del botón principal de la ventana inicial con video'),
('theme_custom_startup_popup_surface', '#140D0E', 'Copia editable: Color base del panel principal de la ventana inicial'),
('theme_custom_startup_popup_border', '#3D1C1A', 'Copia editable: Color del borde y contornos de la ventana inicial'),
('theme_custom_startup_popup_accent', '#25D366', 'Copia editable: Color del icono principal, resaltes y brillo de la ventana inicial'),
('theme_custom_startup_popup_chip', '#0E2B1B', 'Copia editable: Color de fondo para la insignia superior de la ventana inicial'),
('theme_custom_startup_popup_button_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón principal de la ventana inicial'),
('theme_custom_startup_video_popup_surface', '#1A2233', 'Copia editable: Color base del panel principal de la ventana inicial con video'),
('theme_custom_startup_video_popup_border', '#314462', 'Copia editable: Color del borde y contornos de la ventana inicial con video'),
('theme_custom_startup_video_popup_accent', '#F87171', 'Copia editable: Color de detalles destacados y botón de cierre de la ventana inicial con video'),
('theme_custom_startup_video_popup_button_bg', '#25D366', 'Copia editable: Color principal del botón del canal en la ventana inicial con video'),
('theme_custom_startup_video_popup_button_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón principal de la ventana inicial con video');
