-- Tabla de configuración general para la tienda
CREATE TABLE IF NOT EXISTS configuracion_general (
    id INT AUTO_INCREMENT PRIMARY KEY,
    clave VARCHAR(64) NOT NULL UNIQUE,
    valor TEXT NOT NULL,
    descripcion VARCHAR(255) DEFAULT NULL,
    actualizado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    mostrar_a_cliente TINYINT(1) DEFAULT 0 NULL,
    funcion_venta VARCHAR(255) DEFAULT NULL,
    descripcion_venta VARCHAR(255) DEFAULT NULL,
    precio INT DEFAULT NULL,
    comision_venta INT DEFAULT NULL
);

-- Ejemplo de inserción de variables iniciales
INSERT INTO configuracion_general (clave, valor, descripcion) VALUES
('correo_corporativo', '', 'Correo usado para notificaciones'),
('smtp_host', '', 'Host SMTP para envío de correos'),
('smtp_user', '', 'Usuario SMTP'),
('smtp_pass', '', 'Contraseña SMTP'),
('smtp_port', '587', 'Puerto SMTP'),
('smtp_secure', 'tls', 'Tipo de seguridad SMTP'),
('nombre_prefijo', 'TIENDA', 'Texto superior del encabezado de la tienda'),
('nombre_tienda', 'TVirtualGaming', 'Nombre principal visible de la tienda'),
('nombre_tienda_subtitulo', 'Tienda de monedas digitales', 'Texto complementario usado en el título del inicio y en la instalación de la app'),
('logo_tienda', '', 'Ruta del logo visible en el encabezado'),
('fondo_animado', '0', 'Activa o desactiva globalmente la sección de fondo multimedia fijo para el sitio público.'),
('filtros_influencer', '0', 'Activa o desactiva los filtros avanzados y tarjetas resumen del módulo Cupones de Influencers.'),
('guardar_ultimo_id', '0', 'Activa o desactiva el guardado y reutilización del último identificador de jugador usado por el cliente en sus compras.'),
('diferencia_pago', '0', 'Activa o desactiva el flujo de diferencia de pago para montos transferidos por encima o por debajo del total del pedido.'),
('barra_superior', '0', 'Activa o desactiva la barra superior fija con buscador y reubicación del acceso principal del sitio público.'),
('ventana_inicio_juego', '0', 'Activa o desactiva la funcion de ventanas iniciales por juego.'),
('google_analytics_activo', '0', 'Activa o desactiva la inserción del script de Google Analytics o Google Tag en el footer público'),
('google_analytics_script', '', 'Código script completo de Google Analytics o Google Tag que se inserta en el footer público'),
('notificaciones_recargas', '0', 'Activa o desactiva por tenant las notificaciones de recargas en la tienda'),
('verificacion_nombre_api', '0', 'Activa o desactiva por tenant la verificación de nombres de jugador mediante API'),
('api_binance', '0', 'Activa o desactiva la configuracion e integracion de Binance Pay via CoinPal para este tenant.'),
('api_binance_pagonorte', '0', 'Api para verificar movimientos en Binance'),
('api_binance_usuario', '1', 'Activa o desactiva el uso visible de Binance Pay para clientes y procesos automaticos de la tienda cuando el tenant ya tiene disponible api_binance.'),
('api_discord', '0', 'Activa o desactiva la integración base de API Discord para enviar comandos de consulta y pruebas de recarga desde este tenant.'),
('api_discord_webhook_url', '', 'Webhook de Discord usado para enviar mensajes de prueba y comandos controlados al canal configurado.'),
('api_discord_timeout', '10', 'Tiempo máximo en segundos que la sonda webhook de API Discord esperará por la respuesta HTTP de Discord.'),
('api_discord_username', 'VirtualGaming API Discord', 'Nombre visible opcional con el que se publicarán los mensajes enviados por el webhook de API Discord.'),
('api_discord_avatar_url', '', 'Avatar opcional usado por el webhook de API Discord al publicar mensajes de prueba o sondeo.'),
('api_discord_dry_run', '1', 'Activa el modo preventivo para usar primero comandos seguros de precio y pruebas antes de habilitar comandos de recarga reales.'),
('api_discord_probe_command', 'mobile_legends_price', 'Clave del comando seguro por defecto usada para la prueba webhook de API Discord desde el panel administrativo.'),
('api_discord_listener_token', '', 'Token secreto usado por el listener de API Discord para aceptar correlaciones externas de mensajes y actualizar el estado de las ordenes.'),
('recarga_notificaciones_activas', '1', 'Activa o desactiva las notificaciones flotantes de recargas en el sitio público'),
('recarga_notificaciones_logo', '', 'Ruta del logo usado en la notificación flotante de recargas'),
('facebook', '', 'URL de Facebook de la tienda'),
('instagram', '', 'URL de Instagram de la tienda'),
('tiktok', '', 'URL de TikTok de la tienda'),
('whatsapp', '', 'Número o enlace de WhatsApp de la tienda'),
('mensaje_whatsapp', '', 'Mensaje predefinido para el botón flotante de WhatsApp'),
('whatsapp_flotante_activo', '1', 'Activa o desactiva el botón flotante de WhatsApp en el sitio público'),
('whatsapp_channel', '', 'URL del canal de WhatsApp de la tienda'),
('whatsapp_channel_flotante_activo', '1', 'Activa o desactiva el botón flotante del canal de WhatsApp en el sitio público'),
('google_client_id', '', 'Client ID de Google para login y registro social'),
('google_client_secret', '', 'Client Secret de Google para login y registro social'),
('win_points_notification_position', 'bottom-left', 'Posicion de la notificacion flotante de Win Points en la pagina publica.'),
('inicio_popup_tab_habilitado', '1', 'Activa o desactiva globalmente el tab y la función de la ventana inicial'),
('inicio_popup_activo', '1', 'Activa o desactiva la disponibilidad de la ventana inicial normal en el index'),
('inicio_popup_video_activo', '0', 'Activa o desactiva la disponibilidad de la ventana inicial con video en el index'),
('inicio_popup_galeria', '0', 'Activa o desactiva la disponibilidad de la ventana inicial de galería en el index'),
('inicio_popup_modo', '', 'Modo seleccionado para la ventana inicial del index'),
('inicio_popup_frecuencia', 'per_session', 'Frecuencia con la que debe aparecer la ventana inicial en el index'),
('inicio_popup_nombre_canal', 'DanisA Gamer Store', 'Nombre visible del canal en la ventana inicial'),
('inicio_popup_video_url', '', 'Enlace de YouTube usado en la ventana inicial con video'),
('inicio_popup_galeria_imagenes', '[]', 'Listado JSON de imágenes usadas por la ventana inicial de galería'),
('ff_bank_api_base_url', 'https://pagonorte.net', 'Enlace base de la API del banco para consultar movimientos'),
('ff_bank_dias_disponibles', '', 'Dias disponibles reportados por la API del banco al consultar movimientos'),
('binance_pagonorte_token', '', 'Token usado para consultar movimientos y saldo en la API Binance de PagoNorte.'),
('binance_pagonorte_dias_disponibles', '', 'Dias disponibles reportados por la API Binance de PagoNorte al consultar movimientos.'),
('binance_pagonorte_descuento', '0', 'Porcentaje de descuento aplicado cuando se use la verificación Binance de PagoNorte.'),
('binance_pay_merchant_no', '', 'Merchant No configurado para Binance Pay via CoinPal.'),
('binance_pay_secret_key', '', 'Secret Key configurada para Binance Pay via CoinPal.'),
('binance_pay_store_id', '', 'Store ID registrado en CoinPal para esta tienda.'),
('binance_pay_access_token', '', 'Access Token del Store registrado en CoinPal para esta tienda.'),
('binance_pay_store_url', '', 'URL o dominio registrado en CoinPal My Store para esta tienda.'),
('ff_api_usuario', '', 'Usuario para la API de Free Fire'),
('ff_api_clave', '', 'Clave para la API de Free Fire'),
('ff_api_tipo', 'recargaFreefire', 'Tipo para la API de Free Fire'),
('theme_bg_main', '#0A0F14', 'Color base del fondo general de la tienda'),
('theme_bg_alt', '#0E1722', 'Color usado en degradados y secciones secundarias'),
('theme_surface', '#111827', 'Color de tarjetas, paneles y modales'),
('theme_surface_alt', '#181F2A', 'Color alterno para cabecera, dropdowns y paneles internos'),
('theme_primary', '#22D3EE', 'Color principal del brillo, bordes y textos destacados'),
('theme_highlight', '#00FFF7', 'Color de realce para brillos y botones destacados'),
('theme_secondary', '#2DD4BF', 'Color secundario para degradados, hover y efectos'),
('theme_success', '#34D399', 'Color para acciones positivas y estados correctos'),
('theme_warning', '#F59E0B', 'Color para alertas y estados de revisión'),
('theme_danger', '#F87171', 'Color para cancelaciones, errores y alertas críticas'),
('theme_text', '#F8FAFC', 'Color principal del texto en la tienda'),
('theme_text_muted', '#CBD5E1', 'Color de textos secundarios, ayudas y descripciones'),
('theme_price_text', '#22D3EE', 'Color del monto principal en precios de juegos y paquetes'),
('theme_price_muted', '#94A3B8', 'Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_border', '#164E63', 'Color base de bordes, separadores y contenedores'),
('theme_button_primary', '#22D3EE', 'Color principal para botones, acciones y llamadas principales'),
('theme_button_secondary', '#2DD4BF', 'Color secundario para degradados y hover de botones'),
('theme_button_surface', '#0E1722', 'Color base para botones oscuros, menú y tarjetas seleccionables'),
('theme_game_feature_bg', '#0E1722', 'Color de fondo para las caracteristicas visibles en la ficha publica del juego'),
('theme_game_feature_border', '#164E63', 'Color del borde para las caracteristicas visibles en la ficha publica del juego'),
('theme_game_feature_text', '#22D3EE', 'Color del texto para las caracteristicas visibles en la ficha publica del juego'),
('theme_package_feature_bg', '#0F172A', 'Color de fondo para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_package_feature_border', '#164E63', 'Color del borde para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_package_feature_text', '#D8FBFF', 'Color del texto e icono para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_float_whatsapp_bg', '#22C55E', 'Color principal del botón flotante de WhatsApp'),
('theme_float_whatsapp_text', '#F8FAFC', 'Color del texto e icono del botón flotante de WhatsApp'),
('theme_float_channel_bg', '#1F2937', 'Color principal del botón flotante del canal de difusión'),
('theme_float_channel_text', '#F8FAFC', 'Color del texto e icono del botón flotante del canal de difusión'),
('theme_live_notification_bg', '#0F172A', 'Color de fondo de la notificación flotante de recargas'),
('theme_live_notification_border', '#1D4ED8', 'Color del borde y brillo exterior de la notificación flotante de recargas'),
('theme_live_notification_accent', '#22D3EE', 'Color del acento, punto activo y detalles destacados de la notificación de recargas'),
('theme_live_notification_text', '#F8FAFC', 'Color del texto principal de la notificación flotante de recargas'),
('theme_live_notification_muted', '#BFDBFE', 'Color del texto secundario y complementario de la notificación flotante de recargas'),
('theme_custom_bg_main', '#0A0F14', 'Copia editable: Color base del fondo general de la tienda'),
('theme_custom_bg_alt', '#0E1722', 'Copia editable: Color usado en degradados y secciones secundarias'),
('theme_custom_surface', '#111827', 'Copia editable: Color de tarjetas, paneles y modales'),
('theme_custom_surface_alt', '#181F2A', 'Copia editable: Color alterno para cabecera, dropdowns y paneles internos'),
('theme_custom_primary', '#22D3EE', 'Copia editable: Color principal del brillo, bordes y textos destacados'),
('theme_custom_highlight', '#00FFF7', 'Copia editable: Color de realce para brillos y botones destacados'),
('theme_custom_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados, hover y efectos'),
('theme_custom_success', '#34D399', 'Copia editable: Color para acciones positivas y estados correctos'),
('theme_custom_warning', '#F59E0B', 'Copia editable: Color para alertas y estados de revisión'),
('theme_custom_danger', '#F87171', 'Copia editable: Color para cancelaciones, errores y alertas críticas'),
('theme_custom_text', '#F8FAFC', 'Copia editable: Color principal del texto en la tienda'),
('theme_custom_text_muted', '#CBD5E1', 'Copia editable: Color de textos secundarios, ayudas y descripciones'),
('theme_custom_price_text', '#22D3EE', 'Copia editable: Color del monto principal en precios de juegos y paquetes'),
('theme_custom_price_muted', '#94A3B8', 'Copia editable: Color del prefijo "Desde" y la moneda en precios de juegos y paquetes'),
('theme_custom_border', '#164E63', 'Copia editable: Color base de bordes, separadores y contenedores'),
('theme_custom_button_primary', '#22D3EE', 'Copia editable: Color principal para botones, acciones y llamadas principales'),
('theme_custom_button_secondary', '#2DD4BF', 'Copia editable: Color secundario para degradados y hover de botones'),
('theme_custom_button_surface', '#0E1722', 'Copia editable: Color base para botones oscuros, menú y tarjetas seleccionables'),
('theme_custom_game_feature_bg', '#0E1722', 'Copia editable: Color de fondo para las caracteristicas visibles en la ficha publica del juego'),
('theme_custom_game_feature_border', '#164E63', 'Copia editable: Color del borde para las caracteristicas visibles en la ficha publica del juego'),
('theme_custom_game_feature_text', '#22D3EE', 'Copia editable: Color del texto para las caracteristicas visibles en la ficha publica del juego'),
('theme_custom_package_feature_bg', '#0F172A', 'Copia editable: Color de fondo para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_custom_package_feature_border', '#164E63', 'Copia editable: Color del borde para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_custom_package_feature_text', '#D8FBFF', 'Copia editable: Color del texto e icono para las caracteristicas del paquete mostradas en el encabezado de pago minimalista'),
('theme_custom_float_whatsapp_bg', '#22C55E', 'Copia editable: Color principal del botón flotante de WhatsApp'),
('theme_custom_float_whatsapp_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón flotante de WhatsApp'),
('theme_custom_float_channel_bg', '#1F2937', 'Copia editable: Color principal del botón flotante del canal de difusión'),
('theme_custom_float_channel_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón flotante del canal de difusión'),
('theme_custom_live_notification_bg', '#0F172A', 'Copia editable: Color de fondo de la notificación flotante de recargas'),
('theme_custom_live_notification_border', '#1D4ED8', 'Copia editable: Color del borde y brillo exterior de la notificación flotante de recargas'),
('theme_custom_live_notification_accent', '#22D3EE', 'Copia editable: Color del acento, punto activo y detalles destacados de la notificación de recargas'),
('theme_custom_live_notification_text', '#F8FAFC', 'Copia editable: Color del texto principal de la notificación flotante de recargas'),
('theme_custom_live_notification_muted', '#BFDBFE', 'Copia editable: Color del texto secundario y complementario de la notificación flotante de recargas'),
('theme_startup_popup_surface', '#140D0E', 'Color base del panel principal de la ventana inicial'),
('theme_startup_popup_border', '#3D1C1A', 'Color del borde y contornos de la ventana inicial'),
('theme_startup_popup_accent', '#25D366', 'Color del icono principal, resaltes y brillo de la ventana inicial'),
('theme_startup_popup_chip', '#0E2B1B', 'Color de fondo para la insignia superior de la ventana inicial'),
('theme_startup_popup_button_text', '#F8FAFC', 'Color del texto e icono del botón principal de la ventana inicial'),
('theme_startup_video_popup_surface', '#1A2233', 'Color base del panel principal de la ventana inicial con video'),
('theme_startup_video_popup_border', '#314462', 'Color del borde y contornos de la ventana inicial con video'),
('theme_startup_video_popup_accent', '#F87171', 'Color de detalles destacados y botón de cierre de la ventana inicial con video'),
('theme_startup_video_popup_button_bg', '#25D366', 'Color principal del botón del canal en la ventana inicial con video'),
('theme_startup_video_popup_button_text', '#F8FAFC', 'Color del texto e icono del botón principal de la ventana inicial con video'),
('theme_custom_startup_popup_surface', '#140D0E', 'Copia editable: Color base del panel principal de la ventana inicial'),
('theme_custom_startup_popup_border', '#3D1C1A', 'Copia editable: Color del borde y contornos de la ventana inicial'),
('theme_custom_startup_popup_accent', '#25D366', 'Copia editable: Color del icono principal, resaltes y brillo de la ventana inicial'),
('theme_custom_startup_popup_chip', '#0E2B1B', 'Copia editable: Color de fondo para la insignia superior de la ventana inicial'),
('theme_custom_startup_popup_button_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón principal de la ventana inicial'),
('theme_custom_startup_video_popup_surface', '#1A2233', 'Copia editable: Color base del panel principal de la ventana inicial con video'),
('theme_custom_startup_video_popup_border', '#314462', 'Copia editable: Color del borde y contornos de la ventana inicial con video'),
('theme_custom_startup_video_popup_accent', '#F87171', 'Copia editable: Color de detalles destacados y botón de cierre de la ventana inicial con video'),
('theme_custom_startup_video_popup_button_bg', '#25D366', 'Copia editable: Color principal del botón del canal en la ventana inicial con video'),
('theme_custom_startup_video_popup_button_text', '#F8FAFC', 'Copia editable: Color del texto e icono del botón principal de la ventana inicial con video');

UPDATE configuracion_general
SET mostrar_a_cliente = 1,
    funcion_venta = 'API Binance Pay',
    descripcion_venta = 'Activa pagos automaticos con Binance Pay via CoinPal para este tenant.',
    precio = COALESCE(precio, 0),
    comision_venta = COALESCE(comision_venta, 0)
WHERE clave = 'api_binance';

UPDATE configuracion_general
SET mostrar_a_cliente = 1,
    funcion_venta = 'API Discord',
    descripcion_venta = 'Automatiza pruebas webhook y futuras integraciones de comandos de Discord para consultas de precios y recargas controladas.',
    precio = COALESCE(precio, 60),
    comision_venta = COALESCE(comision_venta, 0)
WHERE clave = 'api_discord';

UPDATE configuracion_general
SET mostrar_a_cliente = 1,
    funcion_venta = 'Ventana Inicial Galería',
    descripcion_venta = 'Muestra una ventana inicial tipo galería con imágenes promocionales, botón al canal de WhatsApp y cierre controlado al entrar al index.',
    precio = 15
WHERE clave = 'inicio_popup_galeria';
